#!/command/with-contenv bash

if [[ -f "/app/tubesync/bilibili.py" && -f "/app/bilibili.json" ]];then
    cd /app || exit
    s6-setuidgid abc python3 /app/tubesync/bilibili.py --database /app/bilibili.json
fi

# sleep INTERVAL seconds and then exit. s6 will re-run this service.
# This simulates a cron job.
sleep "${INTERVAL_BILIBILI:-600}"
