#!/command/with-contenv bash

if [[ -f "/app/tubesync/youtube.py" && -f "/app/youtube.json" ]];then
    cd /app || exit
    s6-setuidgid abc python3 /app/tubesync/youtube.py --database /app/youtube.json
fi

# sleep INTERVAL seconds and then exit. s6 will re-run this service.
# This simulates a cron job.
sleep "${INTERVAL_YOUTUBE:-600}"
